name: CI HablaBienAI

on:
  push:
    branches:
      - main
      - Jhon-Modulo-captura-de-medios
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Validar frontend
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias frontend
        run: npm install
        working-directory: frontend

      - name: Compilar frontend
        run: npm run build
        working-directory: frontend

  backend:
    name: Validar backend
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias backend
        run: pip install -r requirements.txt
        working-directory: backend

      - name: Ejecutar pruebas backend
        run: pytest
        working-directory: backend
